package abm.jakaria.school;
// Generated Aug 30, 2015 4:08:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contractus generated by hbm2java
 */
@Entity
@Table(name="contractus"
    ,catalog="schoolmanagement"
)
public class Contractus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String mobile;
     private String message;

    public Contractus() {
    }

	
    public Contractus(String name) {
        this.name = name;
    }
    public Contractus(String name, String email, String mobile, String message) {
       this.name = name;
       this.email = email;
       this.mobile = mobile;
       this.message = message;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobile", length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="message", length=50)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


