package abm.jakaria.school;
// Generated Aug 30, 2015 4:08:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="schoolmanagement"
)
public class Student  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String fathername;
     private String gender;
     private Date dob;
     private String resigion;
     private String mobile;
     private String praddress;
     private String peraddress;
     private String nationality;
     private String class_;
     private String sgroup;
     private String shift;
     private Integer roll;
     private String session;
     private String email;
     private byte[] photo;
     private String tname;

    public Student() {
    }

	
    public Student(String name) {
        this.name = name;
    }
    public Student(String name, String fathername, String gender, Date dob, String resigion, String mobile, String praddress, String peraddress, String nationality, String class_, String sgroup, String shift, Integer roll, String session, String email, byte[] photo, String tname) {
       this.name = name;
       this.fathername = fathername;
       this.gender = gender;
       this.dob = dob;
       this.resigion = resigion;
       this.mobile = mobile;
       this.praddress = praddress;
       this.peraddress = peraddress;
       this.nationality = nationality;
       this.class_ = class_;
       this.sgroup = sgroup;
       this.shift = shift;
       this.roll = roll;
       this.session = session;
       this.email = email;
       this.photo = photo;
       this.tname = tname;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="fathername", length=45)
    public String getFathername() {
        return this.fathername;
    }
    
    public void setFathername(String fathername) {
        this.fathername = fathername;
    }

    
    @Column(name="gender", length=8)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dob", length=19)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="resigion", length=15)
    public String getResigion() {
        return this.resigion;
    }
    
    public void setResigion(String resigion) {
        this.resigion = resigion;
    }

    
    @Column(name="mobile", length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="praddress", length=45)
    public String getPraddress() {
        return this.praddress;
    }
    
    public void setPraddress(String praddress) {
        this.praddress = praddress;
    }

    
    @Column(name="peraddress", length=45)
    public String getPeraddress() {
        return this.peraddress;
    }
    
    public void setPeraddress(String peraddress) {
        this.peraddress = peraddress;
    }

    
    @Column(name="nationality", length=20)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="class", length=10)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="sgroup", length=20)
    public String getSgroup() {
        return this.sgroup;
    }
    
    public void setSgroup(String sgroup) {
        this.sgroup = sgroup;
    }

    
    @Column(name="shift", length=10)
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }

    
    @Column(name="roll")
    public Integer getRoll() {
        return this.roll;
    }
    
    public void setRoll(Integer roll) {
        this.roll = roll;
    }

    
    @Column(name="session", length=15)
    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="photo")
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    
    @Column(name="tname", length=45)
    public String getTname() {
        return this.tname;
    }
    
    public void setTname(String tname) {
        this.tname = tname;
    }




}


